class_name StateNamesMiniBossDeathHighPriest extends StateEnemy

const IDLE = "StateIdle"
const STRAFE = "StateStrafe"
const SWIPE = "StateAtkSwipe"
const TELEGRAPH_SWIPE = "StateTelegraphSwipe"
const STUNNED = "StateTelegraph"
const THINKING = "StateThinking"
const SACRIFICE = "StateSacrifice"
const DAGGER_CONE = "StateDaggerCone"
const TELEGRAPH_DAGGER_CONE = "StateTelegraphDaggerCone"
const DAGGER_EXPLOSION = "StateDaggerExplosion"
const TELEGRAPH_DAGGER_EXPLOSION = "StateTelegraphDaggerExplosion"
const DAGGER_CIRCLING = "StateDaggerCircling"
const TELEGRAPH_DAGGER_CIRCLING = "StateTelegraphDaggerCircling"
const TELEPORT = "StateTeleport"
const CAST_SHIELD = "StateCastShield"
